// Code generated by protoc-gen-catalystgo. DO NOT EDIT.

package kv

import (
	context "context"
	_ "embed"

	go_grpc_middleware "github.com/grpc-ecosystem/go-grpc-middleware"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
)

//go:embed kv.swagger.json
var swaggerJSON []byte

type KVServiceServiceDesc struct {
	svc KVServiceServer
	i   grpc.UnaryServerInterceptor
}

func NewKVServiceServiceDesc(svc KVServiceServer) *KVServiceServiceDesc {
	return &KVServiceServiceDesc{
		svc: svc,
	}
}

func (d *KVServiceServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterKVServiceServer(s, d.svc)
}

func (d *KVServiceServiceDesc) RegisterHTTP(ctx context.Context, mux *runtime.ServeMux) error {
	if d.i == nil {
		return RegisterKVServiceHandlerServer(ctx, mux, d.svc)
	}

	return RegisterKVServiceHandlerServer(ctx, mux, &proxyKVServiceServer{
		KVServiceServer: d.svc,
		interceptor:     d.i,
	})
}

func (d *KVServiceServiceDesc) SwaggerJSON() []byte {
	return swaggerJSON
}

// WithHTTPUnaryInterceptor adds GRPC Server interceptors for the HTTP unary endpoints. Call again to add more.
func (d *KVServiceServiceDesc) WithHTTPUnaryInterceptor(i grpc.UnaryServerInterceptor) {
	if d.i == nil {
		d.i = i
	} else {
		d.i = go_grpc_middleware.ChainUnaryServer(d.i, i)
	}
}

type proxyKVServiceServer struct {
	KVServiceServer
	interceptor grpc.UnaryServerInterceptor
}

func (p *proxyKVServiceServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	info := &grpc.UnaryServerInfo{
		Server:     p.KVServiceServer,
		FullMethod: "/kv.KVService/Get",
	}

	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return p.KVServiceServer.Get(ctx, req.(*GetRequest))
	}

	resp, err := p.interceptor(ctx, req, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}

	return resp.(*GetResponse), nil
}

func (p *proxyKVServiceServer) Set(ctx context.Context, req *SetRequest) (*SetResponse, error) {
	info := &grpc.UnaryServerInfo{
		Server:     p.KVServiceServer,
		FullMethod: "/kv.KVService/Set",
	}

	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return p.KVServiceServer.Set(ctx, req.(*SetRequest))
	}

	resp, err := p.interceptor(ctx, req, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}

	return resp.(*SetResponse), nil
}

func (p *proxyKVServiceServer) Del(ctx context.Context, req *DelRequest) (*DelResponse, error) {
	info := &grpc.UnaryServerInfo{
		Server:     p.KVServiceServer,
		FullMethod: "/kv.KVService/Del",
	}

	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return p.KVServiceServer.Del(ctx, req.(*DelRequest))
	}

	resp, err := p.interceptor(ctx, req, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}

	return resp.(*DelResponse), nil
}
