app:
  name: "raft-kv"

server:
  debug:
    port: 6001
  http:
    port: 7001
  grpc:
    port: 8001
  graceful_shutdown:
    timeout: 10s
    delay: 1s

tracing:
  enabled: true
  provider: "jaeger"  # or "zipkin", "opentelemetry", etc.
  address: "localhost:6831"

vault:
  enable: false
  address: "http://localhost:8200"
  token: ""

realtime_config: # Registered in ETCD (only available when etcd is enabled)
  - name: log_level #
    usage: Log level enum ["ERROR", "WARN", "INFO", "DEBUG"]
    value: "WARN"
    type: string

rate_limiter:
  enable: true
  default:
    limit: 100
    burst: 10

env: # (always available)
  key1: "value1"

secrets: # (only available when vault is disabled)
  key1: "value1"
