services:
  raft-kv-1:
    image: dekuyo/raft-kv:latest
    container_name: raft-kv-1
    ports:
      - "6001:6000"
      - "7001:7000"
      - "8001:8000"
    environment:
      - RAFT_ID=1
      - RAFT_CLUSTER=1@raft-kv-1:8000,2@raft-kv-2:8000,3@raft-kv-3:8000,4@raft-kv-4:8000,5@raft-kv-5:8000
      - BADGER_ENTRY_PATH=/data/entry
      - BADGER_STATE_PATH=/data/state
      - BADGER_KV_PATH=/data/kv
    networks:
      - raft-kv

  raft-kv-2:
    image: dekuyo/raft-kv:latest
    container_name: raft-kv-2
    ports:
      - "6002:6000"
      - "7002:7000"
      - "8002:8000"
    environment:
      - RAFT_ID=2
      - RAFT_CLUSTER=1@raft-kv-1:8000,2@raft-kv-2:8000,3@raft-kv-3:8000,4@raft-kv-4:8000,5@raft-kv-5:8000
      - BADGER_ENTRY_PATH=/data/entry
      - BADGER_STATE_PATH=/data/state
      - BADGER_KV_PATH=/data/kv
    networks:
      - raft-kv

  raft-kv-3:
    image: dekuyo/raft-kv:latest
    container_name: raft-kv-3
    ports:
      - "6003:6000"
      - "7003:7000"
      - "8003:8000"
    environment:
      - RAFT_ID=3
      - RAFT_CLUSTER=1@raft-kv-1:8000,2@raft-kv-2:8000,3@raft-kv-3:8000,4@raft-kv-4:8000,5@raft-kv-5:8000
      - BADGER_ENTRY_PATH=/data/entry
      - BADGER_STATE_PATH=/data/state
      - BADGER_KV_PATH=/data/kv
    networks:
      - raft-kv

  raft-kv-4:
    image: dekuyo/raft-kv:latest
    container_name: raft-kv-4
    ports:
      - "6004:6000"
      - "7004:7000"
      - "8004:8000"
    environment:
      - RAFT_ID=4
      - RAFT_CLUSTER=1@raft-kv-1:8000,2@raft-kv-2:8000,3@raft-kv-3:8000,4@raft-kv-4:8000,5@raft-kv-5:8000
      - BADGER_ENTRY_PATH=/data/entry
      - BADGER_STATE_PATH=/data/state
      - BADGER_KV_PATH=/data/kv
    networks:
      - raft-kv

  raft-kv-5:
    image: dekuyo/raft-kv:latest
    container_name: raft-kv-5
    ports:
      - "6005:6000"
      - "7005:7000"
      - "8005:8000"
    environment:
      - RAFT_ID=5
      - RAFT_CLUSTER=1@raft-kv-1:8000,2@raft-kv-2:8000,3@raft-kv-3:8000,4@raft-kv-4:8000,5@raft-kv-5:8000
      - BADGER_ENTRY_PATH=/data/entry
      - BADGER_STATE_PATH=/data/state
      - BADGER_KV_PATH=/data/kv
    networks:
      - raft-kv

  dozzle:
    image: amir20/dozzle:pr-3419
    container_name: "dozzle"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"

  portainer:
    image: portainer/portainer-ce:2.24.0-alpine
    container_name: "portainer"
    ports:
      - "8090:8000"
      - "9000:9000"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
    raft-kv:
        driver: bridge

volumes:
  data:
