services:
  raft-kv-1:
    image: dekuyo/raft-kv:dev
    container_name: raft-kv-1
    ports:
      - "6001:6000"
      - "7001:7000"
      - "8001:8000"
    environment:
      - LOG_LEVEL=WARN
      # general
      - RAFT_ID=1
      - RAFT_CLUSTER=1@172.16.238.11:8000,2@172.16.238.12:8000,3@172.16.238.13:8000,4@172.16.238.14:8000,5@172.16.238.15:8000
      - RAFT_COMMIT_PERIOD=50
      - RAFT_START_DELAY=1500
      - RAFT_ELECTION_TIMEOUT=150
      # leader
      - RAFT_STALE_PERIOD=200
      - RAFT_HEARTBEAT_PERIOD=50
      - RAFT_HEARTBEAT_BATCH_SIZE=10
      # db
      - BADGER_ENTRY_PATH=/data/entry
      - BADGER_STATE_PATH=/data/state
      - BADGER_KV_PATH=/data/kv
    volumes:
      - raft_data_1:/data
      - ../.:/go/src/github.com/escalopa/raft-kv
    networks:
      raft-kv:
          ipv4_address: 172.16.238.11

  raft-kv-2:
    image: dekuyo/raft-kv:dev
    container_name: raft-kv-2
    ports:
      - "6002:6000"
      - "7002:7000"
      - "8002:8000"
    environment:
      - LOG_LEVEL=WARN
      # general
      - RAFT_ID=2
      - RAFT_CLUSTER=1@172.16.238.11:8000,2@172.16.238.12:8000,3@172.16.238.13:8000,4@172.16.238.14:8000,5@172.16.238.15:8000
      - RAFT_COMMIT_PERIOD=50
      - RAFT_START_DELAY=1500
      - RAFT_ELECTION_TIMEOUT=150
      # leader
      - RAFT_STALE_PERIOD=200
      - RAFT_HEARTBEAT_PERIOD=50
      - RAFT_HEARTBEAT_BATCH_SIZE=10
      # db
      - BADGER_ENTRY_PATH=/data/entry
      - BADGER_STATE_PATH=/data/state
      - BADGER_KV_PATH=/data/kv
    volumes:
      - raft_data_2:/data
      - ../.:/go/src/github.com/escalopa/raft-kv
    networks:
      raft-kv:
          ipv4_address: 172.16.238.12

  raft-kv-3:
    image: dekuyo/raft-kv:dev
    container_name: raft-kv-3
    ports:
      - "6003:6000"
      - "7003:7000"
      - "8003:8000"
    environment:
      - LOG_LEVEL=WARN
      # general
      - RAFT_ID=3
      - RAFT_CLUSTER=1@172.16.238.11:8000,2@172.16.238.12:8000,3@172.16.238.13:8000,4@172.16.238.14:8000,5@172.16.238.15:8000
      - RAFT_COMMIT_PERIOD=50
      - RAFT_START_DELAY=1500
      - RAFT_ELECTION_TIMEOUT=150
      # leader
      - RAFT_STALE_PERIOD=200
      - RAFT_HEARTBEAT_PERIOD=50
      - RAFT_HEARTBEAT_BATCH_SIZE=10
      # db
      - BADGER_ENTRY_PATH=/data/entry
      - BADGER_STATE_PATH=/data/state
      - BADGER_KV_PATH=/data/kv
    volumes:
      - raft_data_3:/data
      - ../.:/go/src/github.com/escalopa/raft-kv
    networks:
      raft-kv:
          ipv4_address: 172.16.238.13

  raft-kv-4:
    image: dekuyo/raft-kv:dev
    container_name: raft-kv-4
    ports:
      - "6004:6000"
      - "7004:7000"
      - "8004:8000"
    environment:
      - LOG_LEVEL=WARN
      # general
      - RAFT_ID=4
      - RAFT_CLUSTER=1@172.16.238.11:8000,2@172.16.238.12:8000,3@172.16.238.13:8000,4@172.16.238.14:8000,5@172.16.238.15:8000
      - RAFT_COMMIT_PERIOD=50
      - RAFT_START_DELAY=1500
      - RAFT_ELECTION_TIMEOUT=150
      # leader
      - RAFT_STALE_PERIOD=200
      - RAFT_HEARTBEAT_PERIOD=50
      - RAFT_HEARTBEAT_BATCH_SIZE=10
      # db
      - BADGER_ENTRY_PATH=/data/entry
      - BADGER_STATE_PATH=/data/state
      - BADGER_KV_PATH=/data/kv
    volumes:
      - raft_data_4:/data
      - ../.:/go/src/github.com/escalopa/raft-kv
    networks:
      raft-kv:
          ipv4_address: 172.16.238.14

  raft-kv-5:
    image: dekuyo/raft-kv:dev
    container_name: raft-kv-5
    ports:
      - "6005:6000"
      - "7005:7000"
      - "8005:8000"
    environment:
      - LOG_LEVEL=WARN
      # general
      - RAFT_ID=5
      - RAFT_CLUSTER=1@172.16.238.11:8000,2@172.16.238.12:8000,3@172.16.238.13:8000,4@172.16.238.14:8000,5@172.16.238.15:8000
      - RAFT_COMMIT_PERIOD=50
      - RAFT_START_DELAY=1500
      - RAFT_ELECTION_TIMEOUT=150
      # leader
      - RAFT_STALE_PERIOD=200
      - RAFT_HEARTBEAT_PERIOD=50
      - RAFT_HEARTBEAT_BATCH_SIZE=10
      # db
      - BADGER_ENTRY_PATH=/data/entry
      - BADGER_STATE_PATH=/data/state
      - BADGER_KV_PATH=/data/kv
    volumes:
      - raft_data_5:/data
      - ../.:/go/src/github.com/escalopa/raft-kv
    networks:
      raft-kv:
          ipv4_address: 172.16.238.15

  dozzle:
    image: amir20/dozzle:pr-3419
    container_name: "dozzle"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"

  portainer:
    image: portainer/portainer-ce:2.24.0-alpine
    container_name: "portainer"
    ports:
      - "8090:8000"
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
    raft-kv:
        driver: bridge

volumes:
  portainer_data:
  raft_data_1:
  raft_data_2:
  raft_data_3:
  raft_data_4:
  raft_data_5: